apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  nginx__default.conf: |-
{{ .Files.Get "files/nginx/default.conf" | indent 4 }}
  nginx__nginx.conf: |-
{{ .Files.Get "files/nginx/nginx.conf" | indent 4 }}