{{- range $name, $vals := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: {{ default "Opaque" $vals.type }}
data:
{{- range $k, $v := $vals }}
  {{- if ne $k "type" }}
  {{ $k }}: {{ $v }}{{ end -}}
  {{ end -}}
{{ end -}}
